version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5898:5000"
    env_file:
      - stack.env
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - FLASK_APP=webapp.core_app:app
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=${TIMEZONE:-America/Denver}
    volumes:
      - video_pipeline_manager_db_data:/app/webapp/database
      - ./webapp/previews:/app/webapp/previews
      - ./webapp/processed_videos:/app/webapp/processed_videos
    restart: unless-stopped
    networks:
      video_generation:
        ipv4_address: 10.20.0.14

networks:
  video_generation:
    external: true
    name: "Video Generation"

volumes:
  video_pipeline_manager_db_data: